
variables:
- name: moduleName
  value: PwshTenable

trigger:
- master

stages:

- stage: Build
  jobs:

  - job: Build
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - checkout: self
      clean: true
      persistCredentials: true
    - template: build-steps.yml
      parameters:
        moduleName: ${{ variables.moduleName }}

- template: test-stage.yml
  parameters:
    PS51: false

- stage: Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:

  - job: Commit_Updated_Manifest
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - checkout: self
      clean: true
      persistCredentials: true
    - download: current
      artifact: files
    - pwsh: |
        Move-Item -Path '$(Pipeline.Workspace)/files/${{ variables.moduleName }}.psd1' -Destination '${{ variables.moduleName }}.psd1' -Confirm:$false -Force
        git add ${{ variables.moduleName }}.psd1
        git -c "user.name=$(Build.RequestedFor)" -c "user.email=$(Build.RequestedForEmail)" commit -m "Updated module version: $(Build.BuildNumber) [skip ci]"
        git push origin HEAD:master
      workingDirectory: '$(Build.SourcesDirectory)'

  - job: Github_Release
    dependsOn: Commit_Updated_Manifest
    steps:
    - task: GithubRelease@0
      displayName: 'Create GitHub Release'
      inputs:
        target: master
        gitHubConnection: RobFaie
        repositoryName: telstrapurple/${{ variables.moduleName }}
        tagSource: manual
        tag: $(Build.BuildNumber)
        assets: |
          $(Pipeline.Workspace)/zip/*.zip
          $(Pipeline.Workspace)/tar/*.tar
